---
title: "emorsa"
author: "YW"
date: "11/12/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(rwebppl)
library(here)
library(ggplot2)
library(tidyverse)
library(langcog)
library(patchwork)
library(ggpubr)
library(lme4)
library(brms)
rm(list = ls())
```
### state: human
```{r}
d.raw <- read.csv(here("/data/201221EMO-RSA_MAIN_STATE_January 13, 2021_15.51.csv"))
d <- d.raw %>%
  slice(-1:-2) %>%
  filter(Consent != "") %>%
  select(ResponseId, starts_with("PUtt_"), starts_with("NUtt_")) %>%
  pivot_longer(cols = c(starts_with("PUtt_"), starts_with("NUtt_")), 
               names_to = "trial", values_to = "response") %>%
  separate(trial, into=c("utt","exp","race", "gender","question", "random")) %>%
  rename(id = `ResponseId`) %>%
  mutate(question = case_when(question == "GT" ~ "true state",
                              question == "check" ~ "check"),
         condition = case_when(utt == "PUtt" & exp == "PExp" ~ "PU_PE",
                               utt == "PUtt" & exp == "NExp" ~ "PU_NE",
                               utt == "NUtt" & exp == "PExp" ~ "NU_PE",
                               utt == "NUtt" & exp == "NExp" ~ "NU_NE"),
         condition = fct_relevel(condition, "PU_PE", "PU_NE", "NU_PE", "NU_NE"),
         response = fct_relevel(response, "1", "2", "3", "4", "5", "6")) %>%
  select(-random) %>%
  filter(response != "") 

checks <- d %>%
  filter(question == "check") %>%
  mutate(check_score = case_when(race == "A" & grepl("H", response, ignore.case = TRUE) ~ 1,
                                 race == "B" & grepl("O", response, ignore.case = TRUE) ~ 1,
                                 race == "L" & grepl("U", response, ignore.case = TRUE) ~ 1,
                                 race == "W" & grepl("L", response, ignore.case = TRUE) ~ 1,
                                 TRUE ~ 0)) %>%
  group_by(id) %>%
  summarize(perc_correct = mean(check_score))

ggplot(checks, aes(perc_correct)) +
  geom_histogram(binwidth=.01) +
  theme_bw() +
  xlab("accuracy on check questions") +
  ylab("number of participants")

# Only include those who got all check questions correct
d <- full_join(d, checks) %>%
  filter(perc_correct == 1) %>%
  filter

d.state <- d %>%
  filter(question=="true state") %>%
  mutate(utt = case_when(utt == "PUtt" ~ "good",
                         utt == "NUtt" ~ "bad"),
         exp = case_when(exp == "PExp" ~ "smile",
                         exp == "NExp" ~ "frown"),
         utt = fct_relevel(utt, "good"),
         exp = fct_relevel(exp, "smile"),
         condition = case_when(condition=="PU_PE" ~ "good smile",
                               condition=="NU_NE" ~ "bad frown",
                               condition=="PU_NE" ~ "good frown",
                               condition=="NU_PE" ~ "bad smile"),
         condition = factor(condition, levels=c("good smile", "bad frown", "good frown", "bad smile")),
         response = as.numeric(response)) %>%
  select(-perc_correct)
```
###infGoal & socGoal: human
```{r}
dGoal.raw <- read.csv(here("data/201221EMO-RSA_MAIN_COMMGOALS_PREREGISTERED_DONOTCHANGE_January 13, 2021_20.41.csv"))
dGoal <- dGoal.raw %>%
  slice(-1:-2) %>%
  filter(Q358 != "", Q129 != "test") %>%
  select(ResponseId, starts_with("PUtt_"), starts_with("NUtt_")) %>%
  pivot_longer(cols = c(starts_with("PUtt_"), starts_with("NUtt_")), 
               names_to = "trial", values_to = "response") %>%
  separate(trial, into=c("utt","exp","race", "gender","question", "random")) %>%
  rename(id = `ResponseId`) %>%
  mutate(question = case_when(question == "feed" ~ "informational goal",
                              question == "nice" ~ "social goal",
                              question == "check" ~ "check"),
         condition = case_when(utt == "PUtt" & exp == "PExp" ~ "PU_PE",
                               utt == "PUtt" & exp == "NExp" ~ "PU_NE",
                               utt == "NUtt" & exp == "PExp" ~ "NU_PE",
                               utt == "NUtt" & exp == "NExp" ~ "NU_NE"),
         condition = fct_relevel(condition, "PU_PE", "PU_NE", "NU_PE", "NU_NE"),
         response = fct_relevel(response, "1", "2", "3", "4")) %>%
  select(-random) %>%
  filter(response != "") 

checksGoal <- dGoal %>%
  filter(question == "check") %>%
  mutate(check_score = case_when(race == "A" & grepl("H", response, ignore.case = TRUE) ~ 1,
                                 race == "B" & grepl("O", response, ignore.case = TRUE) ~ 1,
                                 race == "L" & grepl("U", response, ignore.case = TRUE) ~ 1,
                                 race == "W" & grepl("L", response, ignore.case = TRUE) ~ 1,
                                 TRUE ~ 0)) %>%
  group_by(id) %>%
  summarize(perc_correct = mean(check_score))

ggplot(checksGoal, aes(perc_correct)) +
  geom_histogram(binwidth=.01) +
  theme_bw() +
  xlab("accuracy on check questions") +
  ylab("number of participants")

# Only include those who got all check questions correct
dGoal <- full_join(dGoal, checksGoal) %>%
  filter(perc_correct == 1) %>%
  filter

dGoal2 <- dGoal %>%
  filter(question!="check") %>%
  mutate(utt = case_when(utt == "PUtt" ~ "good",
                         utt == "NUtt" ~ "bad"),
         exp = case_when(exp == "PExp" ~ "smile",
                         exp == "NExp" ~ "frown"),
         utt = fct_relevel(utt, "good"),
         exp = fct_relevel(exp, "smile"),
         condition = case_when(condition=="PU_PE" ~ "good smile",
                               condition=="NU_NE" ~ "bad frown",
                               condition=="PU_NE" ~ "good frown",
                               condition=="NU_PE" ~ "bad smile"),
         condition = factor(condition, levels=c("good smile", "bad frown", "good frown", "bad smile")),
         response = as.numeric(response)) %>%
  select(-perc_correct)
d.infGoal <- dGoal2[dGoal2$question == "informational goal",]
d.socGoal <- dGoal2[dGoal2$question == "social goal",]
```

### analysis



```{r}
contrasts(d.state$utt)  <- contr.sum(2) / 2
contrasts(d.state$exp)  <- contr.sum(2) / 2

# Bayesian mixed-effects model
rs.state <- brm(response ~ utt * exp + 
               (1 + utt*exp | id) + 
               (1 + utt*exp | race),
             data = d.state,
             family = cumulative(link = "logit", 
                                 threshold = "flexible"),
             chains = 4, cores = 4, iter = 8000,
             file = "brm_state_maximal_8k_4chain")

summary(rs.state)
```

Regression model
<!--

y ~ b0 + b1*u + b2*e + b3*e*u

u = {-0.5 (bad), 0.5 (good)}
e = {-0.5 (frown), 0.5 (smile)}

good_smile = b0 + 0.5 * b1 + 0.5 * b2 + 0.25 * b3
good_frown = b0 + 0.5 * b1 - 0.5 * b2 - 0.25 * b3
bad_smile = b0 - 0.5 * b1 + 0.5 * b2 - 0.25 * b3
bad_frown = b0 - 0.5 * b1 - 0.5 * b2 + 0.25 * b3

good_{smile - frown} = b2 + 0.5 * b3
bad_{smile - frown} =  b2 - 0.5 * b3

smile_{good - bad} = b1 + 0.5 * b3
frown_{good - bad} = b1 - 0.5 * b3

good_frown - bad_smile = b1 - b2
good_smile - bad_frown = b1 + b2
-->

```{r}
h_good_smile_frown = c(
  h_good_smile_frown = "exp1 + 0.5 * utt1:exp1 = 0"
)

h_bad_smile_frown = c(
  h_bad_smile_frown = "exp1 - 0.5 * utt1:exp1 = 0"
)

h_smile_good_bad = c(
  h_smile_good_bad = "utt1 + 0.5 * utt1:exp1 = 0"
)

h_frown_good_bad = c(
  h_frown_good_bad = "utt1 - 0.5 * utt1:exp1 = 0"
)

h_goodFrown_badSmile = c(
  h_goodFrown_badSmile = "utt1 - exp1 = 0"
)

h_goodSmile_badFrown = c(
  h_goodSmile_badFrown = "utt1 + exp1 = 0"
)



hypothesis(rs.state, c(h_good_smile_frown, h_bad_smile_frown,
                       h_smile_good_bad, h_frown_good_bad,
                       h_goodFrown_badSmile, h_goodSmile_badFrown))
```



```{r}
contrasts(d.infGoal$utt)  <- contr.sum(2) / 2
contrasts(d.infGoal$exp)  <- contr.sum(2) / 2


rs.infGoal <- brm(response ~ utt * exp + 
                    (1 + utt*exp|id) + 
                    (1 + utt*exp|race),
                data = d.infGoal,
               family = cumulative(link = "logit", 
                                   threshold = "flexible"),
               chains = 4, cores = 4, iter = 8000,
               file = "brm_infGoal_maximal_8k_4chain")
summary(rs.infGoal)

hypothesis(rs.infGoal, c(h_good_smile_frown, h_bad_smile_frown,
                       h_smile_good_bad, h_frown_good_bad,
                       h_goodFrown_badSmile, h_goodSmile_badFrown))

```

```{r}
contrasts(d.socGoal$utt)  <- contr.sum(2) / 2
contrasts(d.socGoal$exp)  <- contr.sum(2) / 2


rs.socGoal <- brm(response ~ utt * exp + (1 + utt*exp|id) + (1 + utt*exp|race),
               data = d.socGoal,
              family = cumulative(link = "logit", 
                                   threshold = "flexible"),
               chains = 4, cores = 4, iter = 8000,
               file = "brm_socGoal_maximal_8k_4chain")


summary(rs.socGoal)

hypothesis(rs.socGoal, c(h_good_smile_frown, h_bad_smile_frown,
                       h_smile_good_bad, h_frown_good_bad,
                       h_goodFrown_badSmile, h_goodSmile_badFrown))
```
