---
title: "semantics"
author: "Yang Wu"
date: "12/22/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(here)
library(ggplot2)
library(tidyverse)
library(langcog)
rm(list = ls())
```

```{r}
d.raw <- read.csv(here("models/201221EMO-RSA_SEMANTICS_December 22, 2020_17.46.csv"))
d <- d.raw %>%
  slice(-1:-9) %>% # remove preview and pilot data
  select(ResponseId, starts_with("A_F"), starts_with("W_M"), 
         starts_with("B_F"), starts_with("L_M"), starts_with("Check")) %>%
  pivot_longer(cols = c(starts_with("A_F"), starts_with("W_M"), 
                        starts_with("B_F"), starts_with("L_M")), 
               names_to = "trial", values_to = "response") %>%
  separate(trial, into=c("race","gender","trial", "state")) %>%
  rename(id = `ResponseId`) %>%
  filter(response != "") %>%
  mutate(response = case_when(response == "Yes" ~ 1,
                              response == "No" ~ 0),
         trial = case_when(trial == "Good" ~ "good",
                          trial == "Bad" ~ "bad",
                          trial == "Pos" ~ "smile",
                          trial == "Neg" ~ "frown"),
         trial = factor(trial, levels = c("good", "bad", "smile", "frown")))

checks <- d %>%
  mutate(check_score1 = case_when(grepl("H", Check1, ignore.case = TRUE) ~ 1, TRUE ~ 0),
         check_score2 = case_when(grepl("L", Check2, ignore.case = TRUE) ~ 1, TRUE ~ 0),
         check_score3 = case_when(grepl("O", Check3, ignore.case = TRUE) ~ 1, TRUE ~ 0),
         check_score4 = case_when(grepl("U", Check4, ignore.case = TRUE) ~ 1, TRUE ~ 0)) %>%
  group_by(id) %>%
  summarize(check_perc_correct = mean(c(check_score1, check_score2, check_score3, check_score4)))

ggplot(checks, aes(check_perc_correct)) +
  geom_histogram(binwidth=.01) +
  theme_bw() +
  xlab("accuracy on check questions") +
  ylab("number of participants")

# Only include those who got 75% or more check questions correct
d2 <- full_join(d, checks) %>%
  filter(check_perc_correct == 1) %>%
  filter %>%
  select(-Check1, -Check2, -Check3, -Check4, -check_perc_correct)

#write.csv(d2, here("models/clean_data_semantics.csv"), row.names = FALSE)

semantics <- d2 %>%
  group_by(trial, state) %>%
  multi_boot_standard(col = "response") %>%
  summarize(ci_lower=round(ci_lower, 4),ci_upper=round(ci_upper, 4), mean=round(mean, 4))

pd <- position_dodge(0.2)
ggplot(semantics, aes(x = state, y = mean, group = trial, color=trial)) +
  geom_errorbar(aes(ymin=ci_lower, ymax=ci_upper), width=.1,
                position=pd) +
  geom_line(position=pd) +
  geom_point(aes(shape=trial), position=pd) +
  scale_color_brewer(palette="Set2") +
  theme_bw() 
ggsave(here("models/plot_semantics.pdf"), width=5, height=3)
```


```{r}
df_sem <- read_csv(here("models/clean_data_semantics.csv"))

df_sem %>%
  group_by(trial, state) %>%
  summarize(
    k = sum(response),
    n = n(),
    a = 1 + k,
    b = 1 + n - k 
  ) %>%
  write_csv(., here("models/clean_semantics_params.csv"))
```

